# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a09b50fca3ec3010f8f13bd7ec90f13ac0f18fd996a252cf2a1719fbdfa83268097131019bcfd3bbf9c7823c2506ee6c0fbd6d916ffbcd74a551cb446afa472

test:
  secret_key_base: 2ced9421a8ac1893e35910e6770111bba23f02489b7f56c168e442ff68c438d1a4b5cc577ce20df27c367f98bfc239a190a4b689fedbc80f54754f00d538a5d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
